language: node_js
node_js:
- node
- 8
branches:
  only:
  - master
  - development
notifications:
  slack:
    secure: UQfNSjmJmjc93MFCOCgYI7F0LSnjvI5feHpzO7gHu/df0sMJTbEDm1/whQzSOtAore5S2ua1WvL8l3AabIcmg2BLLKvrEtkS80ruJQKF+ojRB8k2aFEV/6I07e6MB/jlFGutRmsEvsPzTI+5Dkl1UWHwBXMAFvureL1wVuBtxQ2bpdpPDhFTo0cY1crAr7cyUFqFlhsUu9oh21jTBmNH60EC5KILpF6/GXzFu/HZwdzyX0Yia6jirEFATjBqmgkYKED2SKM8HqcmtHLtO75oirlwKZes7Xb1jZ70jTvD4g6DHiwpEj3zolnXbl0lI7qGxL+4BXoUfs1rTdLXdhP4uOyzOEmCNn8IVwiRt1wVsltYHMK21b/u1gPGfzTuQtiZ1uQtXIsP4nsksa5Lo1qhFvqpbOnJbRE3/L7pvlYxrhzM0i0Uf+0N5osmLtRfZMkChH3JmCrLcwYmgT2X2XlM8mj2xx8uvBpy+HAIoPRd/0l8onnURavMhjHUfyXmUKzRuOGLHoyruZhlprWNmfiSrOhEqAzzRHc1uU1reL2BXq39XdL50Lkz7100nNjkGP0gLo9fOKksMoRI5jnMI8KSLZABSx5UKnLok3GJtz/s14spTZYkQ2tgCKj5h5gDXsKplR6mLhR7Mej/APWlp9O7xririRwGhjDsJwgeNwQ0WUM=
