language: node_js
node_js:
- 9
branches:
  only:
  - production
  - master
  - development
notifications:
  slack:
    secure: UQfNSjmJmjc93MFCOCgYI7F0LSnjvI5feHpzO7gHu/df0sMJTbEDm1/whQzSOtAore5S2ua1WvL8l3AabIcmg2BLLKvrEtkS80ruJQKF+ojRB8k2aFEV/6I07e6MB/jlFGutRmsEvsPzTI+5Dkl1UWHwBXMAFvureL1wVuBtxQ2bpdpPDhFTo0cY1crAr7cyUFqFlhsUu9oh21jTBmNH60EC5KILpF6/GXzFu/HZwdzyX0Yia6jirEFATjBqmgkYKED2SKM8HqcmtHLtO75oirlwKZes7Xb1jZ70jTvD4g6DHiwpEj3zolnXbl0lI7qGxL+4BXoUfs1rTdLXdhP4uOyzOEmCNn8IVwiRt1wVsltYHMK21b/u1gPGfzTuQtiZ1uQtXIsP4nsksa5Lo1qhFvqpbOnJbRE3/L7pvlYxrhzM0i0Uf+0N5osmLtRfZMkChH3JmCrLcwYmgT2X2XlM8mj2xx8uvBpy+HAIoPRd/0l8onnURavMhjHUfyXmUKzRuOGLHoyruZhlprWNmfiSrOhEqAzzRHc1uU1reL2BXq39XdL50Lkz7100nNjkGP0gLo9fOKksMoRI5jnMI8KSLZABSx5UKnLok3GJtz/s14spTZYkQ2tgCKj5h5gDXsKplR6mLhR7Mej/APWlp9O7xririRwGhjDsJwgeNwQ0WUM=
deploy:
  provider: heroku
  api_key:
    secure: C/xU16UbEvebXHOrkOfXajA5mUV5/IyHcQYYLpus6qbCyJtAj+qxGq4yIGoTbgQKbU9yQSJriHC3fcWdx/FnyaJRUvN7AafRhhLC/QwNGc21zfUqJlAVlX1GDWrH+ZdktU/9LETPjnDfCQuljA/MmD+Xjm1gxcqfbaJxb+lvcjlaY86vUzsQh7ryHigzA3z9iHBmyQOjawN+ToD8NgKzc8UMYxaZ7tkVWB0G/yfKacxEGvahvI1nwLQTPqlWn13GPVMEKGWKbKv5K5nngSBnG1OgDeQwmk7UHctv24z8Vv/pD4+FxNBsAXR/c5nlXmqcuDr+T1RYe1wEfz5dqnGSX5WkTqDhJGpZ04+7LLkSmVD9tJHMUe6BJj45fe4ZqrznV2TDAY4eNtCkg1wrne06xSj16I7AJoAIoR5cQEjOi4dXgCBUXXmXuxz65FmKujW/TcOUR8VTESWAdQ4TZKdYAR2OAzeBjq+U/cawnxhMCp3/NQQUxX7V6qE/ccOr3RxH9qjojfrW02YPvW2id/+hRbyZgLxtHUcn6MleSitkIa4Sz8a2EOuuW8qyRGw6m7TX7v3WVxeAskOmOCO8JGL2yuaIu/naMv+O6kTkKc3nATP5/ZEZvrHxb8XkwIE0IsTk3vDym/lGHaoiZlBw7WtQKk49aSJOVCw2FD2+TEQ8J8c=
  app:
    development: dev-codepodsapi
    master: staging-codepodsapi
    production: codepodsapi
