language: node_js
node_js:
- node
- 8
branches:
  only:
  - production
  - master
  - development
notifications:
  slack:
    secure: UQfNSjmJmjc93MFCOCgYI7F0LSnjvI5feHpzO7gHu/df0sMJTbEDm1/whQzSOtAore5S2ua1WvL8l3AabIcmg2BLLKvrEtkS80ruJQKF+ojRB8k2aFEV/6I07e6MB/jlFGutRmsEvsPzTI+5Dkl1UWHwBXMAFvureL1wVuBtxQ2bpdpPDhFTo0cY1crAr7cyUFqFlhsUu9oh21jTBmNH60EC5KILpF6/GXzFu/HZwdzyX0Yia6jirEFATjBqmgkYKED2SKM8HqcmtHLtO75oirlwKZes7Xb1jZ70jTvD4g6DHiwpEj3zolnXbl0lI7qGxL+4BXoUfs1rTdLXdhP4uOyzOEmCNn8IVwiRt1wVsltYHMK21b/u1gPGfzTuQtiZ1uQtXIsP4nsksa5Lo1qhFvqpbOnJbRE3/L7pvlYxrhzM0i0Uf+0N5osmLtRfZMkChH3JmCrLcwYmgT2X2XlM8mj2xx8uvBpy+HAIoPRd/0l8onnURavMhjHUfyXmUKzRuOGLHoyruZhlprWNmfiSrOhEqAzzRHc1uU1reL2BXq39XdL50Lkz7100nNjkGP0gLo9fOKksMoRI5jnMI8KSLZABSx5UKnLok3GJtz/s14spTZYkQ2tgCKj5h5gDXsKplR6mLhR7Mej/APWlp9O7xririRwGhjDsJwgeNwQ0WUM=
deploy:
  provider: heroku
  api_key:
    secure: q7V4OFu+pIrEQxK3e/tIxDNqPTYIse0FqouGVH+ap+tr2uQBW4wADvQZOqJcFVwfB8NKQlx/+pxs3fAxA+HObaE70iuedG/RiCsNj2lnAnY1KadM+Ge8shAaOICxH02UC+Lao0Q7SGsY4F6ZqjCZzKMY+HqsQDFivwJ7vzuZKmpn014ZmQH43gpnLLX6EZMoSNUr5dJtDL3VL3t6qFz+fXeZ1mzrghEqVF1Dxt1ZoA0DGScrrITeGl5rIYEDaZe0PxCWun9fz9QW8YxNX3YFn16xIFtPkFPyieY/VtwGM9sKrAHPgF1zTu7LaWRk3ed9shGBvWK5uvqbFd4aNh3AYnJ/62jLHS5LLtrMbTApjxoIZODFWykRchnZ30/h4upmFR3LDytFnH9ueNcb2ulfFv4DLFG2vrdMggdxFrngNgAKPLX+vUpJ7nFikWXGtJredc1es0AOFrJHKoSejpEfAxRggCEgv0evmKM7HlHdgDF1TdDPVmEwVxCv4NmQ5Cdw8/41RPzlzD75EKSD3X49ctVKi/ZCA7o0BezkC87ZT5gXwB1IW8o8MksLkwgwpZS+e6xgUUdvpGKxxjc0aWW+xBJIUrjjYndhQCbTbX1sej3NkoAocftHVd8sGT2UzEPhPI4CLP4nEYHFyPy1lFNbZuJ+HsZymE1VvvYFdXwU8/g=
  app: 
    development: dev-codepodsapi
    master: staging-codepodsapi
    production: codepodsapi